SET SERVEROUTPUT ON;

-- Ejercicio 1
/
CREATE OR REPLACE FUNCTION GET_TOTAL_EMPLOYEES_BY_DEPARTMENT_ID(p_dep_id IN NUMBER)
RETURN NUMBER
IS
    V_TOTAL_EMPLOYEES NUMBER;
BEGIN
    SELECT COUNT(ID) INTO V_TOTAL_EMPLOYEES FROM EMPLEADOS E WHERE E.DEPARTAMENTO_ID = p_dep_id;

    RETURN V_TOTAL_EMPLOYEES;
END;
/
/
BEGIN
    DBMS_OUTPUT.PUT_LINE('La cantidad de empleados para el departarmento de administración es: ' || GET_TOTAL_EMPLOYEES_BY_DEPARTMENT_ID(1230));
END;
/